language: android 
jdk: oraclejdk8
sudo: required

env: 
 - TEST_SUITE=test
 - TEST_SUITE=connectedAndroidTest

android:
  components: 
    - tools
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23 
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-19
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository


before_script:   
  - chmod +x scripts/start_emulator_api_23.sh
  - chmod +x scripts/start_emulator_api_19.sh
  - sh scripts/start_emulator_api_23.sh
  - sh scripts/start_emulator_api_19.sh
  - chmod +x gradlew
 
script:
  - ./gradlew $TEST_SUITE --stacktrace

after_success:
  - chmod +x scripts/start_testcoverage.sh
  - sh scripts/start_testcoverage.sh