language: android 
jdk: oraclejdk8
sudo: required

env:
  - TEST_SUITE=test ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
  - TEST_SUITE=connectedAndroidTest ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
  - TEST_SUITE=test ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
  - TEST_SUITE=connectedAndroidTest ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

android:
  components: 
    - tools
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - android-19
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-19
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository


before_script:   
  - chmod +x scripts/start_emulator.sh
  - sh scripts/start_emulator.sh $ANDROID_TARGET $ANDROID_ABI
  - chmod +x gradlew
 
script:
  - ./gradlew $TEST_SUITE --stacktrace

after_success:
  - chmod +x scripts/start_testcoverage.sh
  - sh scripts/start_testcoverage.sh