language: android 
jdk: oraclejdk8
sudo: true

env:
  - TEST_SUITE=test ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
  - TEST_SUITE=connectedAndroidTest ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

android:
  components: 
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-23
    - android-19
    - sys-img-armeabi-v7a-google_apis-19
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches

before_script:   
  - chmod +x scripts/start_emulator.sh
  - sh scripts/start_emulator.sh $ANDROID_TARGET $ANDROID_ABI
  - chmod +x gradlew
 
script: 
  - ./gradlew $TEST_SUITE -stacktrace

after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | sed 's/\r$//' > screen.png
  - ./imgurbash.sh screen.png

after_success:
  - chmod +x scripts/start_testcoverage.sh
  - sh scripts/start_testcoverage.sh
  - bash <(curl -s https://codecov.io/bash)