language: android 
jdk: oraclejdk8
sudo: true

env:
  - TEST_SUITE=test ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
  - TEST_SUITE=connectedAndroidTest ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

android:
  components: 
    - tools
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository


before_script:   
  - chmod +x scripts/start_emulator.sh
  - sh scripts/start_emulator.sh $ANDROID_TARGET $ANDROID_ABI
  - chmod +x gradlew
 
script:
  - ./gradlew $TEST_SUITE --continue --stacktrace

after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - chmod a+x imgurbash.sh
  - adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > screen.png
  - ./imgurbash.sh screen.png

after_success:
  - chmod +x scripts/start_testcoverage.sh
  - sh scripts/start_testcoverage.sh