language: android 
jdk: oraclejdk8
sudo: true

env: 
 - TEST_SUITE=test
 - TEST_SUITE=connectedAndroidTest

android:
  components: 
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23 
    - sys-img-armeabi-v7a-android-23
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository


before_script:   
  - chmod a+x start_emulator.sh
  if [ "${TEST_SUITE}" = "connectedAndroidTest" ]; then 
    sh ./start_emulator.sh 
  fi
  - chmod +x gradlew
  - adb shell pm grant org.digitalcampus.mobile.learning android.permission.READ_PHONE_STATE
  - adb shell pm grant org.digitalcampus.mobile.learning android.permission.READ_EXTERNAL_STORAGE
  - adb shell pm grant org.digitalcampus.mobile.learning android.permission.WRITE_EXTERNAL_STORAGE
 
script:
  - ./gradlew $TEST_SUITE --stacktrace

after_success:
  - ./gradlew createDebugCoverageReport --stacktrace