name: Android Tests

on: push

jobs:
  build:
    name: Gradle build pass
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@test-github-actions
        name: Checkout branch
      - name: set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew assembleNormalDebug

  junit:
    name: Unit tests
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@test-github-actions
        name: Checkout branch

      - name: Run Unit tests
        run: ./gradlew testNormalDebugUnitTest

      - name: Bundle unit tests results artifact
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testNormalDebugUnitTest

  tests:
    name: Instrumentation tests
    needs: build
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [28, 29, 30]
        target: [default, google_apis]
    steps:
      - name: Checkout branch
        uses: actions/checkout@test-github-actions

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Run all instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          emulator-options: -no-window -gpu host
          disable-animations: true
          script: ./gradlew connectedNormalDebugAndroidTest
